$ErrorActionPreference = 'Stop'

function Replace-InFile {
    param(
        [Parameter(Mandatory=$true)][string]$Path,
        [Parameter(Mandatory=$true)][string[][]]$Replacements
    )

    $text = Get-Content -LiteralPath $Path -Raw
    foreach ($pair in $Replacements) {
        $text = $text.Replace($pair[0], $pair[1])
    }
    Set-Content -LiteralPath $Path -Value $text -Encoding UTF8
}

Replace-InFile -Path 'frontend/src/pages/Settings.tsx' -Replacements @(
    @('sitePassword (optional)', 'Site password (optional)'),
    @('enable PASSWORD Fill in when', 'Fill in when PASSWORD is enabled'),
    @('Only effective for supported platforms;ChatGPT,Cursor,Grok,Kiro,Tavily Support browser mode,OpenBlockLabs Only pure protocols are supported.', 'Only supported platforms use this setting; ChatGPT, Cursor, Grok, Kiro, and Tavily support browser mode, while OpenBlockLabs supports protocol mode only.'),
    @('only CF Worker Effective:OnThe domain name level will be verified later, and the domain name contains at least 2 letters and 2 number.', 'Only applies to CF Worker: when enabled, it validates the domain depth and requires at least 2 letters and 2 digits in the domain.'),
    @('For example 2=example.com,3=a.example.com,4=a.b.example.com.', 'For example: 2=example.com, 3=a.example.com, 4=a.b.example.com.'),
    @('Please go above firstAdd domain.', 'Please add a domain above first.'),
    @('onlyEnabled domainsWill participate in registration; click on the enabled label to remove it directly.', 'Only enabled domains participate in registration; click an enabled tag to remove it directly.'),
    @('${label} Backfill completed:Success ${d.success} / ${d.total}', '${label} backfill completed: success ${d.success} / ${d.total}'),
    @('${label} Backfill results', '${label} backfill result'),
    @('${label} backfillFailed', '${label} backfill failed'),
    @('switchFailed', 'Switch failed'),
    @('IntegrationsTable of contents:', 'Integrations directory:'),
    @('confirmUninstall ${item.label}?`nmeetingStopservice andDeletelocalIntegrationsTable of contents.', 'Confirm uninstall ${item.label}?`nThis will stop the service and delete the local integrations directory.'),
    @('Backfill existing Grok account', 'Backfill existing Grok accounts'),
    @('Backfill existing Kiro account', 'Backfill existing Kiro accounts'),
    @('WithdrawSuccess! Quota:${redeemedAmountUSD !== null ? formatDisplayNumber(redeemedAmountUSD, 2) : \'-\'} Redeem code:${redeemCode || \'-\'}', 'Withdrawal successful! Amount: ${redeemedAmountUSD !== null ? formatDisplayNumber(redeemedAmountUSD, 2) : \'-\'} Code: ${redeemCode || \'-\'}'),
    @('please firstOnContributionFunction', 'Please enable Contribution first'),
    @('Please fill in firstServer address', 'Please enter the server address first'),
    @('Quota information has been refreshed', 'Balance information refreshed'),
    @('Get quota informationFailed', 'Failed to fetch balance information'),
    @('Please fill in first API key', 'Please enter the API key first'),
    @('confirmWithdraw?`nPress ${redeemAmount} initiateWithdrawask', 'Confirm withdrawal?`nA withdrawal request for ${redeemAmount} will be submitted'),
    @('WithdrawSuccess! Quota:${amount !== null ? formatDisplayNumber(amount, 2) : \'-\'} Redeem code:${code || \'-\'}', 'Withdrawal successful! Amount: ${amount !== null ? formatDisplayNumber(amount, 2) : \'-\'} Code: ${code || \'-\'}'),
    @('WithdrawSuccess', 'Withdrawal successful'),
    @('The server did not return available key', 'The server did not return an available key'),
    @('Created and populated API key, please clickSave configuration', 'Created and populated the API key. Click Save configuration.'),
    @('Request new key Failed', 'Failed to request a new key'),
    @('Please enter your email', 'Please enter an email'),
    @('Please fill in the customization firstServer address', 'Please enter the custom server address first'),
    @('bindingSuccess!token Automatically filled in, please clickSave configuration', 'Binding successful! The token has been filled automatically. Click Save configuration.'),
    @('bindingSuccess', 'Binding successful'),
    @('bindingFailed', 'Binding failed'),
    @('please firstBind emailget token', 'Please bind an email to obtain a token first'),
    @('Information has been refreshed', 'Information refreshed'),
    @('OnContributionAfter mode, registerSuccessAccounts will only be uploaded toContributionserver', 'When Contribution mode is enabled, successfully registered accounts will be uploaded only to the Contribution server'),
    @('CPA / CodexProxy / Sub2API Automatic uploading will be disabled to avoid repeated submissions.', 'Automatic CPA / CodexProxy / Sub2API uploads will be disabled to avoid duplicate reporting.'),
    @('Currently this function isxemTransfer station under testing If you are interested, you can join the group to learn more', 'This feature is currently being tested on the xem relay. Join the group if you\'re interested.'),
    @('transfer stationhttps://ai.xem8k5.top/ Group number634758974', 'Relay: https://ai.xem8k5.top/ Group: 634758974'),
    @('whetherOn', 'Enable'),
    @('Codex2API(xemtransfer station)', 'Codex2API (xem relay)'),
    @('CustomizeContributionsystem', 'Custom Contribution system'),
    @('Please enterServer address', 'Please enter the server address'),
    @('Leave it blank and click the button on the right to create it automatically.', 'Leave blank and use the button on the right to create one automatically'),
    @('CustomizeServer address', 'Custom server address'),
    @('Enter email address to bind account', 'Enter an email to bind the account'),
    @('binding', 'Bind'),
    @('Bind emailautofill after', 'Auto-filled after binding the email'),
    @('Refresh information', 'Refresh info'),
    @('ContributionFunction has beenOff,OnThen you can get the server and key information.', 'Contribution is off. Turn it on to view server and key information.'),
    @('Server information', 'Server information'),
    @('Number of accounts:', 'Account count:'),
    @('total amount:', 'Total quota:'),
    @('Used credit:', 'Used quota:'),
    @('remaining balance:', 'Remaining quota:'),
    @('Used proportion:', 'Used %:'),
    @('Remaining proportion:', 'Remaining %:'),
    @('Number of converted accounts:', 'Equivalent accounts:'),
    @('key information', 'Key information'),
    @('Balance:', 'Balance:'),
    @('source:', 'Source:'),
    @('Number of bound accounts:', 'Bound accounts:'),
    @('Settlement amount:', 'Settlement amount:'),
    @('WithdrawAmount', 'Withdrawal amount'),
    @('Withdrawal confirmation', 'Confirm withdrawal'),
    @('ContributionFunction has beenOff,OnInformation can be obtained later.', 'Contribution is off. Turn it on to view the information.'),
    @('Balance information', 'Balance information'),
    @('ContributionRecord', 'Contribution records'),
    @('Pending:', 'Pending:'),
    @('The passwords entered twice are inconsistent', 'The two passwords do not match'),
    @('Password protection is enabled', 'Password protection enabled'),
    @('Password protectedOff', 'Password protection disabled'),
    @('The new passwords entered twice are inconsistent', 'The two new passwords do not match'),
    @('Password has been updated', 'Password updated'),
    @('Two-factor authentication is enabled', 'Two-factor authentication enabled'),
    @('Two-factor authentication isOff', 'Two-factor authentication disabled'),
    @('Password protected access', 'Access password protection'),
    @('Enabled', 'Enabled'),
    @('Not enabled', 'Disabled'),
    @('When enabled, a password is required to access the page. Default is notOn, available to anyone with access to this address.', 'When enabled, visitors must enter a password to access the page. It is disabled by default, so anyone who can reach this address can use it.'),
    @('Set access password', 'Set access password'),
    @('Please enter password', 'Please enter a password'),
    @('At least 6 Bit', 'At least 6 characters'),
    @('Confirm Password', 'Confirm password'),
    @('Please enter again', 'Please enter it again'),
    @('Enter password again', 'Re-enter the password'),
    @('Enable password protection', 'Enable password protection'),
    @('Password protection is currently enabled,OffAnyone can access it without a password.', 'Password protection is currently enabled; if you turn it off, anyone can access it without a password.'),
    @('OffPassword protection', 'Disable password protection'),
    @('Change password', 'Change password'),
    @('Current Password', 'Current password'),
    @('Please enter current password', 'Please enter the current password'),
    @('New Password', 'New password'),
    @('Please enter new password', 'Please enter the new password'),
    @('New password (at least 6 Bit)', 'New password (at least 6 characters)'),
    @('Enter new password again', 'Re-enter the new password'),
    @('Update password', 'Update password'),
    @('Two-factor authentication (2FA)', 'Two-factor authentication (2FA)'),
    @('Need to enter when logging in Google Authenticator / Authy wait App in 6 BitCaptcha.', 'You will need to enter the 6-digit code from an authenticator app such as Google Authenticator or Authy when logging in.'),
    @('OffTwo-factor authentication', 'Disable two-factor authentication'),
    @('When enabled, an authenticator will be required in addition to the password when logging in App in 6 BitCaptcha, greatly improvedSecuritysex.', 'When enabled, logging in requires the 6-digit code from your authenticator app in addition to your password, greatly improving security.'),
    @('OnTwo-factor authentication', 'Enable two-factor authentication'),
    @('1. Use validator App Scan the QR code below', '1. Scan the QR code below with your authenticator app'),
    @('Can't scan the QR code? Enter the key manually:', "Can't scan it? Enter the secret manually:"),
    @('2. enter App shown in 6 BitCaptchato confirm binding', '2. Enter the 6-digit code shown in the app to confirm binding'),
    @('Please enterCaptcha', 'Please enter the code'),
    @('6 digits', '6 digits'),
    @('Confirm enable', 'Confirm enable'),
    @('CF Worker At least one domain name needs to be enabled', 'CF Worker requires at least one enabled domain'),
    @('The domain name level must be greater than or equal to 2 integer', 'Domain depth must be an integer greater than or equal to 2'),
    @('saveSuccess', 'Saved successfully'),
    @('overall situationConfiguration', 'Global configuration'),
    @('ConfigurationSave persistence and use it automatically for registration tasks', 'Configuration is saved persistently and used automatically by registration tasks')
)

Replace-InFile -Path 'frontend/src/components/settings/MailImportPanel.tsx' -Replacements @(
    @('batchDelete failed', 'Batch delete failed'),
    @('Emailfolder', 'Email folder'),
    @('operate', 'Action'),
    @('confirmDeletethisEmail?', 'Confirm deleting this email?'),
    @('Emailimport', 'Email import'),
    @('Through the unified import interface, import content into the correspondingEmailAccount pool.', 'Use the unified import interface to import content into the corresponding email account pool.'),
    @('EmailFission (alias)', 'Email alias splitting'),
    @('Off by default; when turned on, each originalEmailGenerate random 6 English alias', 'Disabled by default; when enabled, each source email gets a random 6-character English alias'),
    @('Each originalEmailNumber of fissions', 'Aliases per source email'),
    @('Contains the originalEmail', 'Include original email'),
    @('confirmDeletechecked ${selectedRowKeys.length} mailboxes?', 'Confirm deleting the ${selectedRowKeys.length} selected mailboxes?'),
    @('batchDelete', 'Batch delete')
)
